// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdxNbmj9t7ylRpHb43tIgz9B3fQoCP-s8',
    appId: '1:723822954010:web:3a30e8afb131992ee233a3',
    messagingSenderId: '723822954010',
    projectId: 'valyou-25961',
    authDomain: 'valyou-25961.firebaseapp.com',
    storageBucket: 'valyou-25961.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkbLXr5O9ScSEXQu8PfSshuI8ZmBlEV3U',
    appId: '1:723822954010:android:8110f84991be949be233a3',
    messagingSenderId: '723822954010',
    projectId: 'valyou-25961',
    storageBucket: 'valyou-25961.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATuqxaphBSbkC_YTKM5tPMi7gK3T7xPuA',
    appId: '1:723822954010:ios:171b226d47571672e233a3',
    messagingSenderId: '723822954010',
    projectId: 'valyou-25961',
    storageBucket: 'valyou-25961.appspot.com',
    iosClientId: '723822954010-qgalo6qp04rmmk0avd6ka6oeqipjrv7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.valyou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATuqxaphBSbkC_YTKM5tPMi7gK3T7xPuA',
    appId: '1:723822954010:ios:171b226d47571672e233a3',
    messagingSenderId: '723822954010',
    projectId: 'valyou-25961',
    storageBucket: 'valyou-25961.appspot.com',
    iosClientId: '723822954010-qgalo6qp04rmmk0avd6ka6oeqipjrv7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.valyou',
  );
}
